// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides an AI agent to answer questions about Informatica IDMC.
 *
 * - askIdmcQuestion - A function that allows users to ask questions about Informatica IDMC and receive AI-generated answers.
 * - AskIdmcQuestionInput - The input type for the askIdmcQuestion function.
 * - AskIdmcQuestionOutput - The return type for the askIdmcQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskIdmcQuestionInputSchema = z.object({
  question: z.string().describe('The question about Informatica IDMC.'),
});
export type AskIdmcQuestionInput = z.infer<typeof AskIdmcQuestionInputSchema>;

const AskIdmcQuestionOutputSchema = z.object({
  answer: z.string().describe('The AI-generated answer to the question.'),
});
export type AskIdmcQuestionOutput = z.infer<typeof AskIdmcQuestionOutputSchema>;

export async function askIdmcQuestion(input: AskIdmcQuestionInput): Promise<AskIdmcQuestionOutput> {
  return askIdmcQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askIdmcQuestionPrompt',
  input: {schema: AskIdmcQuestionInputSchema},
  output: {schema: AskIdmcQuestionOutputSchema},
  prompt: `You are an AI assistant that helps users learn Informatica IDMC by answering their questions. Answer the following question:

Question: {{{question}}}`,
});

const askIdmcQuestionFlow = ai.defineFlow(
  {
    name: 'askIdmcQuestionFlow',
    inputSchema: AskIdmcQuestionInputSchema,
    outputSchema: AskIdmcQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
